env:
  token: "ENCRYPTED[!df122d4d9cfc211804e6184ff23e7eeb9e8b31df07f24e6dfa24901a68395f3a1723eb70db2ec3b1d2193841bc1108e2!]"

  chat_id: "ENCRYPTED[!aa2d76c404c234eaf041c246a927b86dd13ba093f5175cdcbd421d6b0b020074eea1a6427f4fa86b02506bb5f39372d9!]"


task:
  name: "Kernel Build.."
  timeout_in: 60m
  container:
    image: nexgang/ubuntu:latest
    cpu: 8
    memory: 32G
    stateful: true
    greedy: true
  Build_script:

    - sudo apt update
    - sudo apt upgrade -y
    - sudo apt install bc python2 pigz -y
    - git clone --depth=1 https://github.com/mizdrake7/Graveyard_r5x -b uclamp k
    - cd k
    - bash build.sh
